/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    media: Media;
    'users-app': UsersApp;
    pedidos: Pedido;
    category: Category;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {
    landing: Landing;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users-app".
 */
export interface UsersApp {
  id: string;
  UserImage: string | Media;
  Nombre: string;
  Apellido: string;
  Edad: number;
  Telfono?: string | null;
  UserName: string;
  Pais: string;
  TitularDeTarjeta?: string | null;
  TarjetaNumero?: string | null;
  FechaExpiracion?: string | null;
  CCV?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pedidos".
 */
export interface Pedido {
  id: string;
  Artista: string;
  Album: string;
  Estado: string;
  Costo: string;
  Imagen: string;
  Usuario: string | UsersApp;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "category".
 */
export interface Category {
  id: string;
  NombreDelGenero: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'users-app';
        value: string | UsersApp;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landing".
 */
export interface Landing {
  id: string;
  Logo: string | Media;
  MenuOptions?:
    | {
        Nombre: string;
        NombreDelBloque: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'menuOption';
      }[]
    | null;
  Interfaz?:
    | (
        | {
            Title: string;
            Descripcion: string;
            Imagen: string | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            CaracteristicaNombre: string;
            CaracteristicaDescripcion: string;
            CaracteristicaNombre2: string;
            CaracteristicaDescripcion2: string;
            CaracteristicaNombre3?: string | null;
            CaracteristicaDescripcion3?: string | null;
            CaracteristicaNombre4?: string | null;
            CaracteristicaDescripcion4?: string | null;
            SplineURLAnimationLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'personalizcion-block-landing';
          }
        | {
            ItemsCarrusel: string | Category;
            id?: string | null;
            blockName?: string | null;
            blockType: 'carrusel-landing';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}